### PR TITLE
Made client side sorting of missions and mods case insensitive

### PR DESCRIPTION
**Pull request by Najsr**
Title explains it well

### CODE REVIEW

**Comment by Dahlgren** [comment]
The comparator can be simplified into

```js
function(i) { return i.get('name').toLowerCase(); }
```

**Comment by Frozen-byte** [comment]
`localeCompare` has advantage to respect special Characters very well (äaâáà, etc). Also it has it's very own case-insensetive option: `{ ignorePunctuation: true }`

**Comment by Dahlgren** [comment]
That's a very good point, `localeCompare` is definitely a better choice!

**Comment by Dahlgren** [comment]
Thanks for the contribution!

**Pull request merged**
