### PR TITLE
add "modsPath" config parameter

### PR DESCRIPTION
**Pull request by Fusselwurm**
Add "modsPath" config parameter to be able to separate game install path from mod collection.
Not sure if that should be a relative or absolute path. In view of linux compatibility it should be relative, I seem to remember 🤔

### CODE REVIEW

**Comment by Dahlgren** [comment]
Yes, Linux breaks on absolute paths. There's some additional management of this in the Steam Workshop branch. I've had an idea to move some of that more "advanced" logic to the current version. That would allow for more than one mod folder as well.

**Comment by Dahlgren** [comment]
Fixes #68

**Comment by Fusselwurm** [comment]
wait. non of this works.

**Comment by Fusselwurm** [comment]
(will re-open at a later point)

**Pull request closed without merging**
