### PR TITLE
Systemd

### PR DESCRIPTION
**Pull request by NemesisRE**
Documentation to run it as a Service with Systemd.

I'm not a developer but a sysadmin, so hopefully such addition are welcome.

### CODE REVIEW

**Comment by Dahlgren** [comment]
Very nice! :+1: 

The files should probably not be in the lib folder, I have yet to figure out a better folder. I guess there could be more services such as init.d or upstart too later even if systemd is gaining a lot of traction

**Comment by NemesisRE** [comment]
Yes maybe just a "doc" folder in the root

**Comment by Dahlgren** [comment]
Sounds like a good idea! Could you change the folder, squash the commits and rebase it on current master?

**Comment by Dahlgren** [comment]
Moved to wiki, https://github.com/Dahlgren/arma-server-web-admin/wiki/Systemd

**Pull request closed without merging**
